### ISSUE TITLE
infinite zoom colab notebook

### ISSUE THREAD

**Issue by BalintKomjati** [karaage0703/stable-diffusion-colab-tools#1]
hi karaage!
i think this would be a great addition to your collection :)

https://github.com/BalintKomjati/smooth-infinite-zoom

**Comment by karaage0703** [comment]
Thanks for good information!
I can create great video by using colab notebook.
I added this notebook to this repository.

https://user-images.githubusercontent.com/5562157/221350138-df294646-a982-4aea-b3b2-37f45c900a37.mp4

**Comment by BalintKomjati** [comment]
i am happy to see the tool in action! :)
your repo was really helpful when i started my journey with SD!! THX
